/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementsystem.ui.verification;

import java.awt.ComponentOrientation;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import studentmanagementsystem.service.Services;
import studentmanagementsystem.ui.Login.AdminLogin;
import studentmanagementsystem.ui.Login.StudentLogin;
import studentmanagementsystem.utility.Util;
import static studentmanagementsystem.utility.Util.isEmailValid;

/**
 *
 * @author Abhishek Rajput
 */
public class EmailDialog extends javax.swing.JDialog {

    private Object obj;
    private int otpTryCount;
    private String subject;

    /**
     * Creates new form EmailDialog
     *
     * @param object
     */
    public EmailDialog(Object object) {

        if (object == null) {
            return;
        }
        initComponents();
        this.obj = object;

        if (obj instanceof AdminLogin obj) {
            this.setLocationRelativeTo(obj);
        } else if (obj instanceof StudentLogin obj) {
            obj.setComponentOrientation(ComponentOrientation.UNKNOWN);

            this.setLocationRelativeTo(obj);
        }

    }

    // Add a component listener to restrict movement
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sendOtp = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Verify Email");

        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        sendOtp.setText("SendOtp");
        sendOtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendOtpActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email.setToolTipText("");
        email.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(sendOtp)
                        .addGap(51, 51, 51)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(sendOtp)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendOtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendOtpActionPerformed
        if (!Util.isInternetAvailable()) {
            JOptionPane.showMessageDialog(rootPane, "Internet Not connected");
            return;
        }
        if (email.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Input field should not null");
            return;
        }
        if (!isEmailValid(email.getText())) {
            JOptionPane.showMessageDialog(rootPane, "email format Not Valid");
            return;
        }
        if (obj instanceof StudentLogin obj1) {
            try {
                if (Services.getService().isStudentEmailExists(email.getText())) {
                    String name = Services.getService().getAdminNameByEmail(email.getText());
                    verifyObj(name);
                } else {
                    JOptionPane.showMessageDialog(obj1, "Email Not Exist!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(obj1, ex);
                Logger.getLogger(VerifyOtpDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (obj instanceof AdminLogin obj1) {
            try {

                if (Services.getService().isAdminEmailExists(email.getText())) {
                    String name = Services.getService().getAdminNameByEmail(email.getText());

                    verifyObj(name);
                } else {
                    JOptionPane.showMessageDialog(obj1, "Email Not Exist!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(VerifyOtpDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_sendOtpActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased

        Util.setLabelStatus(email, emailLabel, isEmailValid(email.getText()));        // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyReleased

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        Util.setLabelStatus(email, emailLabel, isEmailValid(email.getText()));
    }//GEN-LAST:event_emailKeyTyped

    // next page for verify
    private void verifyObj(String name) {
        otpTryCount = 0;
        try {
            VerifyOtpDialog vod = new VerifyOtpDialog(obj, email.getText(), name);

            vod.setModal(true);
            vod.setVisible(true);
            dispose();

        } catch (Exception exception) {
            JOptionPane.showMessageDialog(rootPane, exception);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton sendOtp;
    // End of variables declaration//GEN-END:variables

}
