/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementsystem.ui.verification;

import java.awt.Component;
import java.awt.Point;
import java.awt.Rectangle;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import studentmanagementsystem.ui.Login.AdminLogin;
import studentmanagementsystem.ui.Login.StudentLogin;
import studentmanagementsystem.ui.forms.AdminRegistrationForm;
import studentmanagementsystem.ui.forms.StudentRegistrationForm;
import studentmanagementsystem.utility.EmailSender;
import studentmanagementsystem.utility.Util;

/**
 *
 * @author Abhishek Rajput
 */
public class VerifyOtpDialog extends javax.swing.JDialog {

    private String email;
    private String otp;
    private String subject;
    private EmailSender emailSender = new EmailSender();


    private final byte OTP_RETRY_LIMIT = 3;
    private int otpTryCount = 0;
    private Object obj;
    private NewPasswordDialog passObj;
    private VerifyOtpDialog vod;
    private String name;

    /**
     * Creates new form passwordForgetDialog p
     *
     * @param object
     * @param email
     */
    public VerifyOtpDialog(Object object, String email, String name) {
        if (vod != null) {
            dispose();
        }

        initComponents();
        setLocationRelativeTo(null);
        this.name = name;
        this.obj = object;
        this.email = email;
        emailLabel.setText(email);
      
        java.awt.EventQueue.invokeLater(() -> {
            sendOtp();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        otpField = new javax.swing.JTextField();
        verifyButton = new javax.swing.JButton();
        resendButton = new javax.swing.JButton();
        timerLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ForgotPassword");
        setResizable(false);

        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        otpField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OTP", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        otpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpFieldActionPerformed(evt);
            }
        });
        otpField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                otpFieldKeyTyped(evt);
            }
        });

        verifyButton.setText("Verify");
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });

        resendButton.setText("Resend");
        resendButton.setToolTipText("Click for Resend Otp");
        resendButton.setEnabled(false);
        resendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resendButtonActionPerformed(evt);
            }
        });

        timerLabel.setText("0:00");

        emailLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        emailLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(timerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otpField, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(resendButton)
                        .addGap(36, 36, 36)
                        .addComponent(verifyButton)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(emailLabel)
                .addGap(28, 28, 28)
                .addComponent(otpField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerLabel)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resendButton)
                    .addComponent(verifyButton))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // send otp
    private void sendOtp() {
        otpTryCount = 0;
        otpField.setText("");
        otpField.setEditable(true);
        verifyButton.setEnabled(true);
        try {
            if (obj instanceof StudentRegistrationForm) {
                sendVerificationMail();
                Util.timer(timerLabel,verifyButton,resendButton);

            } else if (obj instanceof AdminRegistrationForm) {

                sendVerificationMail();
                Util.timer(timerLabel,verifyButton,resendButton);

            } else if (obj instanceof AdminLogin) {
                sendResetMail();
                Util.timer(timerLabel,verifyButton,resendButton);

            } else if (obj instanceof StudentLogin) {
                sendResetMail();
                Util.timer(timerLabel,verifyButton,resendButton);

            }

        } catch (Exception exception) {
            exception.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, exception);
        }
    }

    private void sendVerificationMail() {
        if (emailSender.sendVerificationMail(email, name)) {
            JOptionPane.showMessageDialog(rootPane, "Otp send successfully!");
            resendButton.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Not sent");
        }
    }

    private void sendResetMail() {
        if (emailSender.sendResetMail(email, this.name)) {
            JOptionPane.showMessageDialog(rootPane, "Otp send successfully!");
            resendButton.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Not sent");
        }
    }

    // confirmation dialog
    private void confirmation() {
        int response = JOptionPane.showConfirmDialog(
                rootPane,
                "Do you want to generate new Otp?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
        );

        if (response == JOptionPane.YES_OPTION) {
            java.awt.EventQueue.invokeLater(() -> {
                sendOtp();
            });
        }
    }

    //verify otp
    private void verifyOtp() {
        if (emailSender.verifyOtp(otpField.getText())) {
            dispose();
            if (passObj != null) {
                passObj.dispose();
            }
            passObj = new NewPasswordDialog(obj, email, name);
            passObj.setModal(true);
            passObj.setLocationRelativeTo(this);
            passObj.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Wrong Otp Retry!");
            otpTryCount++;
        }
    }


    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed

        // max 3 try 
        if (otpTryCount < OTP_RETRY_LIMIT) {
            // otp varification
            verifyOtp();
        } else {
            otpField.setEditable(false);
            verifyButton.setEnabled(false);
            JOptionPane.showMessageDialog(rootPane, "Reached Maximum try limit");
            confirmation();
        }
    }//GEN-LAST:event_verifyButtonActionPerformed

    private void resendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resendButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
            sendOtp();
        });

    }//GEN-LAST:event_resendButtonActionPerformed

    private void otpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_otpFieldActionPerformed

    private void otpFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otpFieldKeyTyped
        // only number value allowed

        char c = evt.getKeyChar();
        // only digit allow
        if (!Character.isDigit(c)) {
            evt.consume();
        }

        // set max 6 digit allowed
        if (otpField.getText().length() > 5) {
            evt.consume();
        }

    }//GEN-LAST:event_otpFieldKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField otpField;
    private javax.swing.JButton resendButton;
    private javax.swing.JLabel timerLabel;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
}
