/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementsystem.ui.forms;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import studentmanagementsystem.service.Services;
import studentmanagementsystem.ui.verification.VerifyOtpDialog;
import static studentmanagementsystem.utility.Util.allowDigit;
import static studentmanagementsystem.utility.Util.allowLetterOrSpace;
import static studentmanagementsystem.utility.Util.isEmailValid;
import static studentmanagementsystem.utility.Util.isMobileNoValid;
import static studentmanagementsystem.utility.Util.setLabelStatus;

/**
 *
 * @author Abhishek Rajput
 */
public class AdminRegistrationForm extends javax.swing.JFrame {

    private VerifyOtpDialog vod;

    /**
     * Creates new form AddAdmin
     */
    public AdminRegistrationForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        adminNameLabel = new javax.swing.JLabel();
        adminMobileNoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        adminMobileNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project Image/showAdmin.png"))); // NOI18N

        adminName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminName.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        adminName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNameActionPerformed(evt);
            }
        });
        adminName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adminNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adminNameKeyTyped(evt);
            }
        });

        email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email.setToolTipText("");
        email.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });

        submit.setBackground(Color.GREEN);
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        adminMobileNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminMobileNo.setBorder(javax.swing.BorderFactory.createTitledBorder("MobileNumber"));
        adminMobileNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adminMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adminMobileNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adminMobileNoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(138, 138, 138))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminMobileNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminMobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adminMobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(submit)
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNameActionPerformed

    private void adminNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminNameKeyReleased
        allowLetterOrSpace(evt);
        setLabelStatus(adminName, adminNameLabel, !adminName.getText().equals(""));
    }//GEN-LAST:event_adminNameKeyReleased

    private void adminNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminNameKeyTyped

        allowLetterOrSpace(evt);
        setLabelStatus(adminName, adminNameLabel, !adminName.getText().equals(""));
    }//GEN-LAST:event_adminNameKeyTyped

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        if (email.getText().endsWith(".com")) {
            evt.consume();
        }
        setLabelStatus(email, emailLabel, isEmailValid(email.getText()));        // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyReleased

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        // TODO add your handling code here:
        if (email.getText().endsWith(".com")) {
            evt.consume();
        }
        setLabelStatus(email, emailLabel, isEmailValid(email.getText()));
    }//GEN-LAST:event_emailKeyTyped

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if (isAllFieldValid()) {

            String message = "Do you want to proceed to Verify?";
            // Show a confirmation dialog
            int response = JOptionPane.showConfirmDialog(null, message, "Confirmation", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == response) {
                if (vod != null) {
                    vod.dispose();
                }
                vod = new VerifyOtpDialog(this, email.getText(), adminName.getText());
                vod.setModal(true);
                vod.setLocationRelativeTo(this);
                vod.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "plese make sure all field  ✅");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void adminMobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminMobileNoKeyTyped
        if (adminMobileNo.getText().trim().length() >= 10) {
            evt.consume();
        }
        allowDigit(evt);
        // check mobile numbe is valid or not
        boolean result = isMobileNoValid(adminMobileNo.getText());
        // set status label
        setLabelStatus(adminMobileNo, adminMobileNoLabel, result);
        // TODO add your handling code here:
    }//GEN-LAST:event_adminMobileNoKeyTyped

    private void adminMobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminMobileNoKeyReleased
        if (adminMobileNo.getText().trim().length() >= 10) {
            evt.consume();
        }
        allowDigit(evt);
        // check mobile numbe is valid or not
        boolean result = isMobileNoValid(adminMobileNo.getText());
        // set status label
        setLabelStatus(adminMobileNo, adminMobileNoLabel, result);        // TODO add your handling code here:
    }//GEN-LAST:event_adminMobileNoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminMobileNo;
    private javax.swing.JLabel adminMobileNoLabel;
    private javax.swing.JTextField adminName;
    private javax.swing.JLabel adminNameLabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

    private boolean isAllFieldValid() {
        return adminNameLabel.getText().equals("✅")
                && adminMobileNoLabel.getText().equals("✅")
                && emailLabel.getText().equals("✅");
    }

    private void setFieldStatus() {
        setLabelStatus(adminName, adminNameLabel, false);
        setLabelStatus(adminMobileNo, adminMobileNoLabel, false);
        setLabelStatus(email, emailLabel, false);
    }

    public boolean addAdmin(String password) {
        try {
            Services.getService().addAdmin(adminName.getText(), adminMobileNo.getText(), email.getText(), password);
            return true;
        } catch (SQLException ex) {

            Logger.getLogger(AdminRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }

}
