/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementsystem.ui.forms;

import java.awt.Color;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import studentmanagementsystem.service.Services;
import studentmanagementsystem.model.Student;
import studentmanagementsystem.ui.Login.Login;
import studentmanagementsystem.ui.UiController;
import studentmanagementsystem.ui.admin.HomePage;
import studentmanagementsystem.ui.verification.VerifyOtpDialog;
import studentmanagementsystem.utility.EmailSender;
import static studentmanagementsystem.utility.Util.*;

/**
 *
 * @author vivek
 */
public class StudentRegistrationForm extends javax.swing.JFrame {

    private EmailSender emailSender = new EmailSender();

    /**
     * Creates new form AddStudent
     */
    private javax.swing.JSpinner jSpinner1;
    private Object obj;
    private VerifyOtpDialog vod;

    public StudentRegistrationForm(Object obj) {
        initComponents();
        this.obj = obj;
        setFieldStatus();
        setLocationRelativeTo(null);
    }

    public Student createStudent() {
        // Create a new Student object using the input from the UI components

        return new Student(
                studentName.getText(), // studentName
                Date.valueOf(dateOfBirth.getText()), // age
                (String) gender.getSelectedItem(), // gender
                email.getText(), // email (changed from studentAadhaarNo.getText() as in the original)
                (String) collegeCourse.getSelectedItem(), // collegeCourse
                Integer.parseInt((String) collegeYear.getSelectedItem()), // collegeYear
                studentMobileNo.getText(), // studentMobileNo
                localAddress.getText(), // localAddress
                fatherName.getText(), // fatherName
                fatherAadhaarNo.getText(), // fatherAadhaarNo
                fatherOccupation.getText(), // fatherOccupation
                Double.parseDouble(fatherIncome.getText()), // fatherIncome
                fatherMobileNo.getText(), // fatherMobileNo
                motherName.getText(), // motherName
                motherOccupation.getText(), // motherOccupation
                (String) state.getSelectedItem(), // state
                city.getText(), // city
                permanentAddress.getText(), // address
                studentAadhaarNo.getText() // studentAadhaarNo
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        studentName = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        collegeCourse = new javax.swing.JComboBox<>();
        collegeYear = new javax.swing.JComboBox<>();
        dateOfBirth = new javax.swing.JTextField();
        studentAadhaarNo = new javax.swing.JTextField();
        studentMobileNo = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        studentNameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        collegeCourseLabel = new javax.swing.JLabel();
        dateOfBirthLabel = new javax.swing.JLabel();
        studentAadhaarNoLabel = new javax.swing.JLabel();
        studentMobileNoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        fatherOccupation = new javax.swing.JTextField();
        fatherName = new javax.swing.JTextField();
        fatherIncome = new javax.swing.JTextField();
        fatherAadhaarNo = new javax.swing.JTextField();
        fatherMobileNo = new javax.swing.JTextField();
        motherName = new javax.swing.JTextField();
        motherOccupation = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        fatherNameLabel = new javax.swing.JLabel();
        fatherOccupationLabel = new javax.swing.JLabel();
        fatherIncomeLabel = new javax.swing.JLabel();
        fatherAadhaarNoLabel = new javax.swing.JLabel();
        fatherMobileNoLabel = new javax.swing.JLabel();
        motherNameLabel = new javax.swing.JLabel();
        motherOccupationLabel = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        state = new javax.swing.JComboBox<>();
        city = new javax.swing.JTextField();
        permanentAddress = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        cityLabel = new javax.swing.JLabel();
        permanentAddressLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        localAddressLabel = new javax.swing.JLabel();
        localAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("StudentRegistrationForm");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "StudentDetail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setToolTipText("");

        submit.setBackground(Color.GREEN);
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        cancel.setBackground(Color.RED);
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        studentName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentName.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameActionPerformed(evt);
            }
        });
        studentName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentNameKeyTyped(evt);
            }
        });

        gender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female", "Other" }));
        gender.setBorder(javax.swing.BorderFactory.createTitledBorder("Gender"));
        gender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                genderItemStateChanged(evt);
            }
        });
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        gender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                genderKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                genderKeyTyped(evt);
            }
        });

        collegeCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        collegeCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", " Bachelor of Arts (BA)  ", " Bachelor of Science (BSc)  ", " Bachelor of Commerce (BCom)  ", " Bachelor of Technology (BTech)  ", " Bachelor of Computer Applications (BCA)  ", " Bachelor of Fine Arts (BFA)  ", " Bachelor of Design (B.Des)  ", " Bachelor of Architecture (BArch)  ", " Bachelor of Medicine, Bachelor of Surgery (MBBS)  ", " Bachelor of Pharmacy (BPharm)  ", " Bachelor of Nursing (BSc Nursing)  ", " Bachelor of Laws (LLB)  ", " Bachelor of Education (B.Ed)  ", " Bachelor of Urban Planning (BUP)  ", " Bachelor of Environmental Science (BES)  ", " Bachelor of Agriculture (BSc Agriculture)  ", "Master of Arts (MA) ", "Master of Science (MSc) ", "Master of Commerce (MCom) ", "Master of Technology (MTech) ", "Master of Computer Applications (MCA) ", "Master of Fine Arts (MFA) ", "Master of Design (M.Des) ", "Master of Architecture (MArch) ", "Doctor of Medicine (MD) or Master of Surgery (MS) ", "Master of Pharmacy (MPharm) ", "Master of Nursing (MSc Nursing) ", "Master of Laws (LLM) ", "Master of Education (M.Ed) ", "Master of Urban Planning (MUP) ", "Master of Environmental Science (MES) ", "Master of Agriculture (MSc Agriculture)" }));
        collegeCourse.setBorder(javax.swing.BorderFactory.createTitledBorder("Course"));
        collegeCourse.setOpaque(true);
        collegeCourse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                collegeCourseItemStateChanged(evt);
            }
        });

        collegeYear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        collegeYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        collegeYear.setBorder(javax.swing.BorderFactory.createTitledBorder("Year"));
        collegeYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                collegeYearItemStateChanged(evt);
            }
        });

        dateOfBirth.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateOfBirth.setForeground(new java.awt.Color(153, 153, 153));
        dateOfBirth.setText("YYYY-MM-DD");
        dateOfBirth.setToolTipText("Age should be greater then 18");
        dateOfBirth.setBorder(javax.swing.BorderFactory.createTitledBorder("DateOfBirth"));
        dateOfBirth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateOfBirthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateOfBirthFocusLost(evt);
            }
        });
        dateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthActionPerformed(evt);
            }
        });
        dateOfBirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateOfBirthKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateOfBirthKeyTyped(evt);
            }
        });

        studentAadhaarNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentAadhaarNo.setBorder(javax.swing.BorderFactory.createTitledBorder("Aadhaar Number"));
        studentAadhaarNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAadhaarNoActionPerformed(evt);
            }
        });
        studentAadhaarNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentAadhaarNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentAadhaarNoKeyTyped(evt);
            }
        });

        studentMobileNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentMobileNo.setBorder(javax.swing.BorderFactory.createTitledBorder("MobileNumber"));
        studentMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMobileNoActionPerformed(evt);
            }
        });
        studentMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentMobileNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentMobileNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentMobileNoKeyTyped(evt);
            }
        });

        email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email.setToolTipText("");
        email.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(collegeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(collegeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(studentAadhaarNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentMobileNo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(email))
                    .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collegeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collegeYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentAadhaarNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(studentMobileNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {collegeCourse, collegeYear, dateOfBirth, email, studentMobileNo});

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(collegeCourseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateOfBirthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentAadhaarNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentMobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(studentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(collegeCourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(dateOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(studentAadhaarNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(studentMobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        fatherOccupation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fatherOccupation.setBorder(javax.swing.BorderFactory.createTitledBorder("Occupation"));
        fatherOccupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fatherOccupationKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fatherOccupationKeyTyped(evt);
            }
        });

        fatherName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fatherName.setBorder(javax.swing.BorderFactory.createTitledBorder("Father Name"));
        fatherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fatherNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fatherNameKeyTyped(evt);
            }
        });

        fatherIncome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fatherIncome.setBorder(javax.swing.BorderFactory.createTitledBorder("Father Income"));
        fatherIncome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fatherIncomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fatherIncomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fatherIncomeKeyTyped(evt);
            }
        });

        fatherAadhaarNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fatherAadhaarNo.setBorder(javax.swing.BorderFactory.createTitledBorder("FatherAadhaarNo"));
        fatherAadhaarNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherAadhaarNoActionPerformed(evt);
            }
        });
        fatherAadhaarNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fatherAadhaarNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fatherAadhaarNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fatherAadhaarNoKeyTyped(evt);
            }
        });

        fatherMobileNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fatherMobileNo.setBorder(javax.swing.BorderFactory.createTitledBorder("MobileNumber"));
        fatherMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherMobileNoActionPerformed(evt);
            }
        });
        fatherMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fatherMobileNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fatherMobileNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fatherMobileNoKeyTyped(evt);
            }
        });

        motherName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        motherName.setBorder(javax.swing.BorderFactory.createTitledBorder("Mother Name"));
        motherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherNameActionPerformed(evt);
            }
        });
        motherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                motherNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                motherNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                motherNameKeyTyped(evt);
            }
        });

        motherOccupation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        motherOccupation.setBorder(javax.swing.BorderFactory.createTitledBorder("Occupation"));
        motherOccupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                motherOccupationKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                motherOccupationKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                motherOccupationKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fatherIncomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherOccupationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherAadhaarNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherMobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motherNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motherOccupationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(fatherNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(fatherOccupationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(fatherIncomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(fatherAadhaarNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(fatherMobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(motherNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(motherOccupationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fatherMobileNo)
                            .addComponent(fatherAadhaarNo)
                            .addComponent(fatherIncome)
                            .addComponent(motherName)
                            .addComponent(fatherOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(motherOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(fatherOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fatherIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fatherAadhaarNo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fatherMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(motherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(motherOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        jLayeredPane2.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        state.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Madhya Pradesh", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal" }));
        state.setToolTipText("");
        state.setBorder(javax.swing.BorderFactory.createTitledBorder("State"));
        state.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stateItemStateChanged(evt);
            }
        });

        city.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        city.setBorder(javax.swing.BorderFactory.createTitledBorder("City"));
        city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cityKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityKeyTyped(evt);
            }
        });

        permanentAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        permanentAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));
        permanentAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permanentAddressActionPerformed(evt);
            }
        });
        permanentAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                permanentAddressKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                permanentAddressKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                permanentAddressKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permanentAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(localAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(permanentAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(localAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        localAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        localAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("LocalAddress"));
        localAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                localAddressKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                localAddressKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                localAddressKeyTyped(evt);
            }
        });

        jLayeredPane3.setLayer(state, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(city, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(permanentAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(localAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(permanentAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(city, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(localAddress)
                        .addGap(2, 2, 2)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(permanentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(localAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(submit)
                        .addGap(174, 174, 174)
                        .addComponent(cancel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(submit)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cancel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean addStudent(String password) {
        Student student = createStudent();

        try {
            String mail = this.email.getText();
            if (Services.getService().addStudent(student)) {
                int id = Services.getService().getStudentId(mail);
                if (Services.getService().addStudentLoginDetail(id, mail, password)) {
                    emailSender.sendRegistrationSuccessMail(mail, studentName.getText(), id);
                    JOptionPane.showMessageDialog(null, "Student Added successfully");
                    dispose();
                    return true;
                } else {
                    Services.getService().deleteStudent(id);
                    JOptionPane.showMessageDialog(null, "Student Not added");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Student Not added");
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if (isAllFieldValid()) {

            String message = "Do you want to proceed to Verify?";
            // Show a confirmation dialog
            int response = JOptionPane.showConfirmDialog(null, message, "Confirmation", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == response) {
                if (vod != null) {
                    vod.dispose();
                }
                vod = new VerifyOtpDialog(this, email.getText(), studentName.getText());
                vod.setModal(true);
                vod.setLocationRelativeTo(this);
                vod.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "plese make sure all field  ✅");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        if (obj instanceof HomePage) {
            UiController.getHome().setVisible(true);
            dispose();
        } else if (obj instanceof Login) {
            UiController.getLogin().setVisible(true);
            dispose();

        }

    }//GEN-LAST:event_cancelActionPerformed

    private void studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void permanentAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permanentAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permanentAddressActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void fatherMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherMobileNoActionPerformed

    private void motherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motherNameActionPerformed

    private void dateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfBirthActionPerformed

    private void studentAadhaarNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAadhaarNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentAadhaarNoActionPerformed

    private void dateOfBirthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateOfBirthFocusGained
        // TODO add your handling code here:
        if (dateOfBirth.getText().equals("YYYY-MM-DD")) {
            dateOfBirth.setText("");
            dateOfBirth.setForeground(Color.black);
        }
    }//GEN-LAST:event_dateOfBirthFocusGained

    private void dateOfBirthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateOfBirthFocusLost
        // TODO add your handling code here:
        if (dateOfBirth.getText().equals("")) {
            dateOfBirth.setText("YYYY-MM-DD");
            dateOfBirth.setForeground(Color.gray);
        }
    }//GEN-LAST:event_dateOfBirthFocusLost

    private void studentAadhaarNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentAadhaarNoKeyTyped

        allowDigit(evt);
        if (studentAadhaarNo.getText().length() > 11) {
            evt.consume();
            return;
        }
        System.out.println(studentAadhaarNo.getText().length());
        setLabelStatus(studentAadhaarNo, studentAadhaarNoLabel, studentAadhaarNo.getText().length() > 10);
    }//GEN-LAST:event_studentAadhaarNoKeyTyped

    private void studentMobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentMobileNoKeyTyped
        if (studentMobileNo.getText().trim().length() >= 10) {
            evt.consume();
        }
        allowDigit(evt);
        // check mobile numbe is valid or not
        boolean result = isMobileNoValid(studentMobileNo.getText());
        // set status label
        setLabelStatus(studentMobileNo, studentMobileNoLabel, result);

    }//GEN-LAST:event_studentMobileNoKeyTyped

    private void fatherIncomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherIncomeKeyTyped
        // allow 7 digit
        boolean result = fatherIncome.getText().length() + 1 > 7;
        if (result) {
            evt.consume();
        }
        allowDigit(evt);
        setLabelStatus(fatherIncome, fatherIncomeLabel, fatherIncome.getText().length() + 1 > 4);

    }//GEN-LAST:event_fatherIncomeKeyTyped

    private void fatherAadhaarNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherAadhaarNoKeyTyped
        // only 12 digit allow
        allowDigit(evt);
        if (fatherAadhaarNo.getText().length() > 11) {
            evt.consume();
            return;
        }
        System.out.println(fatherAadhaarNo.getText().length());
        setLabelStatus(fatherAadhaarNo, fatherAadhaarNoLabel, fatherAadhaarNo.getText().length() > 10);
    }//GEN-LAST:event_fatherAadhaarNoKeyTyped

    private void fatherMobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherMobileNoKeyTyped
        if (fatherMobileNo.getText().trim().length() >= 10) {
            evt.consume();
        }
        allowDigit(evt);
        // check mobile numbe is valid or not
        boolean result = isMobileNoValid(fatherMobileNo.getText());
        // set status label
        setLabelStatus(fatherMobileNo, fatherMobileNoLabel, result);
    }//GEN-LAST:event_fatherMobileNoKeyTyped

    private void studentNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentNameKeyTyped

        allowLetterOrSpace(evt);
        setLabelStatus(studentName, studentNameLabel, !studentName.getText().equals(""));

    }//GEN-LAST:event_studentNameKeyTyped

    private void dateOfBirthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateOfBirthKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '-' || dateOfBirth.getText().length() > 9) {
            evt.consume();
        }
        boolean validDate = isValidDate(dateOfBirth.getText()) && isAgeBetween18And30(dateOfBirth.getText());
        System.out.println(validDate);
        setLabelStatus(dateOfBirth, dateOfBirthLabel, validDate);

    }//GEN-LAST:event_dateOfBirthKeyTyped

    private void dateOfBirthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateOfBirthKeyReleased
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '-' || dateOfBirth.getText().length() > 9) {
            evt.consume();
        }
        boolean validDate = isValidDate(dateOfBirth.getText()) && isAgeBetween18And30(dateOfBirth.getText());
        System.out.println(validDate);
        setLabelStatus(dateOfBirth, dateOfBirthLabel, validDate);

    }//GEN-LAST:event_dateOfBirthKeyReleased

    private void studentNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentNameKeyReleased
        allowLetterOrSpace(evt);
        setLabelStatus(studentName, studentNameLabel, !studentName.getText().equals(""));

    }//GEN-LAST:event_studentNameKeyReleased

    private void genderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderKeyPressed

    private void motherNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motherNameKeyTyped
        // TODO add your handling code here:
        allowLetterOrSpace(evt);
        setLabelStatus(motherName, motherNameLabel, !motherName.getText().equals(""));

    }//GEN-LAST:event_motherNameKeyTyped

    private void motherOccupationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motherOccupationKeyTyped
        allowLetterOrSpace(evt);
        setLabelStatus(motherOccupation, motherOccupationLabel, !motherOccupation.getText().equals(""));

    }//GEN-LAST:event_motherOccupationKeyTyped

    private void fatherOccupationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherOccupationKeyTyped
        // TODO add your handling code here:
        allowLetterOrSpace(evt);
        setLabelStatus(fatherOccupation, fatherOccupationLabel, !fatherOccupation.getText().equals(""));
    }//GEN-LAST:event_fatherOccupationKeyTyped

    private void fatherNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherNameKeyTyped
        // TODO add your handling code here:
        allowLetterOrSpace(evt);
        setLabelStatus(fatherName, fatherNameLabel, !fatherName.getText().equals(""));
    }//GEN-LAST:event_fatherNameKeyTyped

    private void cityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityKeyTyped
        // TODO add your handling code here:
        allowLetterOrSpace(evt);
        setLabelStatus(city, cityLabel, !city.getText().equals(""));
    }//GEN-LAST:event_cityKeyTyped

    private void studentMobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentMobileNoKeyReleased
        // TODO add your handling code here:
        if (studentMobileNo.getText().trim().length() >= 10) {
            evt.consume();
        }
        allowDigit(evt);
        // check mobile numbe is valid or not
        boolean result = isMobileNoValid(studentMobileNo.getText());
        // set status label
        setLabelStatus(studentMobileNo, studentMobileNoLabel, result);        // TODO add your handling code here:
    }//GEN-LAST:event_studentMobileNoKeyReleased

    private void studentAadhaarNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentAadhaarNoKeyReleased
        // only 12 digit allow
        allowDigit(evt);
        if (studentAadhaarNo.getText().length() > 11) {
            evt.consume();
            return;
        }
        System.out.println(studentAadhaarNo.getText().length());
        setLabelStatus(studentAadhaarNo, studentAadhaarNoLabel, studentAadhaarNo.getText().length() > 11);
    }//GEN-LAST:event_studentAadhaarNoKeyReleased

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped

        setLabelStatus(email, emailLabel, isEmailValid(email.getText()));

    }//GEN-LAST:event_emailKeyTyped

    private void genderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genderKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_genderKeyTyped

    private void genderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_genderItemStateChanged
        // TODO add your handling code here:

        boolean result = !gender.getSelectedItem().toString().equalsIgnoreCase("None");

        setLabelStatus(gender, genderLabel, result);

    }//GEN-LAST:event_genderItemStateChanged

    private void collegeCourseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_collegeCourseItemStateChanged
        // TODO add your handling code here:
        boolean result = !collegeCourse.getSelectedItem().toString().equalsIgnoreCase("None");

        setLabelStatus(collegeCourse, collegeCourseLabel, result);

    }//GEN-LAST:event_collegeCourseItemStateChanged

    private void collegeYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_collegeYearItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_collegeYearItemStateChanged

    private void stateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stateItemStateChanged
        // TODO add your handling code here:
        boolean result = !state.getSelectedItem().toString().equals("None");

        setLabelStatus(state, stateLabel, result);

    }//GEN-LAST:event_stateItemStateChanged

    private void permanentAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_permanentAddressKeyTyped
        // TODO add your handling code here:
        setLabelStatus(permanentAddress, permanentAddressLabel, !permanentAddress.getText().equals(""));

    }//GEN-LAST:event_permanentAddressKeyTyped

    private void localAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localAddressKeyTyped
        // TODO add your handling code here:
        setLabelStatus(localAddress, localAddressLabel, !localAddress.getText().equals(""));
    }//GEN-LAST:event_localAddressKeyTyped

    private void fatherAadhaarNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherAadhaarNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherAadhaarNoActionPerformed

    private void studentMobileNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentMobileNoKeyPressed

    }//GEN-LAST:event_studentMobileNoKeyPressed

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased

        setLabelStatus(email, emailLabel, isEmailValid(email.getText()));        // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyReleased

    private void fatherNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherNameKeyReleased
        allowLetterOrSpace(evt);
        setLabelStatus(fatherName, fatherNameLabel, !fatherName.getText().equals(""));        // TODO add your handling code here:
    }//GEN-LAST:event_fatherNameKeyReleased

    private void fatherOccupationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherOccupationKeyReleased
        allowLetterOrSpace(evt);
        setLabelStatus(fatherOccupation, fatherOccupationLabel, !fatherOccupation.getText().equals(""));        // TODO add your handling code here:
    }//GEN-LAST:event_fatherOccupationKeyReleased

    private void fatherIncomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherIncomeKeyReleased
        // TODO add your handling code here:
        // allow 7 digit
        boolean result = fatherIncome.getText().length() + 1 > 7;
        if (result) {
            evt.consume();
        }
        allowDigit(evt);
        setLabelStatus(fatherIncome, fatherIncomeLabel, fatherIncome.getText().length() + 1 > 4);

    }//GEN-LAST:event_fatherIncomeKeyReleased

    private void fatherIncomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherIncomeKeyPressed

    }//GEN-LAST:event_fatherIncomeKeyPressed

    private void fatherAadhaarNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherAadhaarNoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherAadhaarNoKeyPressed

    private void fatherMobileNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherMobileNoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherMobileNoKeyPressed

    private void motherNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motherNameKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_motherNameKeyPressed

    private void motherOccupationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motherOccupationKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_motherOccupationKeyPressed

    private void cityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityKeyPressed

    private void permanentAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_permanentAddressKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_permanentAddressKeyPressed

    private void localAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localAddressKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_localAddressKeyPressed

    private void fatherAadhaarNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherAadhaarNoKeyReleased
        // only 12 digit allow
        allowDigit(evt);
        if (fatherAadhaarNo.getText().length() > 11) {
            evt.consume();
            return;
        }
        System.out.println(fatherAadhaarNo.getText().length());
        setLabelStatus(fatherAadhaarNo, fatherAadhaarNoLabel, fatherAadhaarNo.getText().length() > 11);        // TODO add your handling code here:
    }//GEN-LAST:event_fatherAadhaarNoKeyReleased

    private void fatherMobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherMobileNoKeyReleased
        if (studentMobileNo.getText().trim().length() >= 10) {
            evt.consume();
        }
        allowDigit(evt);
        // check mobile numbe is valid or not
        boolean result = isMobileNoValid(fatherMobileNo.getText());
        // set status label
        setLabelStatus(fatherMobileNo, fatherMobileNoLabel, result);         // TODO add your handling code here:
    }//GEN-LAST:event_fatherMobileNoKeyReleased

    private void motherNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motherNameKeyReleased
        allowLetterOrSpace(evt);
        setLabelStatus(motherName, motherNameLabel, !motherName.getText().equals(""));        // TODO add your handling code here:
    }//GEN-LAST:event_motherNameKeyReleased

    private void motherOccupationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motherOccupationKeyReleased
        allowLetterOrSpace(evt);
        setLabelStatus(motherOccupation, motherOccupationLabel, !motherOccupation.getText().equals(""));        // TODO add your handling code here:
    }//GEN-LAST:event_motherOccupationKeyReleased

    private void cityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityKeyReleased
        allowLetterOrSpace(evt);
        setLabelStatus(city, cityLabel, !city.getText().equals(""));          // TODO add your handling code here:
    }//GEN-LAST:event_cityKeyReleased

    private void permanentAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_permanentAddressKeyReleased
        setLabelStatus(permanentAddress, permanentAddressLabel, !permanentAddress.getText().equals(""));
        // TODO add your handling code here:
    }//GEN-LAST:event_permanentAddressKeyReleased

    private void localAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localAddressKeyReleased
        setLabelStatus(localAddress, localAddressLabel, !localAddress.getText().equals(""));
        // TODO add your handling code here:
    }//GEN-LAST:event_localAddressKeyReleased

    private void studentMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentMobileNoActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new StudentRegistrationForm().setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField city;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JComboBox<String> collegeCourse;
    private javax.swing.JLabel collegeCourseLabel;
    private javax.swing.JComboBox<String> collegeYear;
    private javax.swing.JTextField dateOfBirth;
    private javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField fatherAadhaarNo;
    private javax.swing.JLabel fatherAadhaarNoLabel;
    private javax.swing.JTextField fatherIncome;
    private javax.swing.JLabel fatherIncomeLabel;
    private javax.swing.JTextField fatherMobileNo;
    private javax.swing.JLabel fatherMobileNoLabel;
    private javax.swing.JTextField fatherName;
    private javax.swing.JLabel fatherNameLabel;
    private javax.swing.JTextField fatherOccupation;
    private javax.swing.JLabel fatherOccupationLabel;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField localAddress;
    private javax.swing.JLabel localAddressLabel;
    private javax.swing.JTextField motherName;
    private javax.swing.JLabel motherNameLabel;
    private javax.swing.JTextField motherOccupation;
    private javax.swing.JLabel motherOccupationLabel;
    private javax.swing.JTextField permanentAddress;
    private javax.swing.JLabel permanentAddressLabel;
    private javax.swing.JComboBox<String> state;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField studentAadhaarNo;
    private javax.swing.JLabel studentAadhaarNoLabel;
    private javax.swing.JTextField studentMobileNo;
    private javax.swing.JLabel studentMobileNoLabel;
    private javax.swing.JTextField studentName;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
//methods

    private void setFieldStatus() {
        setLabelStatus(studentName, studentNameLabel, false);
        setLabelStatus(gender, genderLabel, false);
        setLabelStatus(collegeCourse, collegeCourseLabel, false);
        setLabelStatus(dateOfBirth, dateOfBirthLabel, false);
        setLabelStatus(studentAadhaarNo, studentAadhaarNoLabel, false);
        setLabelStatus(studentMobileNo, studentMobileNoLabel, false);
        setLabelStatus(email, emailLabel, false);
        setLabelStatus(fatherName, fatherOccupationLabel, false);
        setLabelStatus(fatherOccupation, fatherNameLabel, false);
        setLabelStatus(fatherIncome, fatherIncomeLabel, false);
        setLabelStatus(fatherAadhaarNo, fatherAadhaarNoLabel, false);
        setLabelStatus(fatherMobileNo, fatherMobileNoLabel, false);
        setLabelStatus(motherName, motherNameLabel, false);
        setLabelStatus(motherOccupation, motherOccupationLabel, false);
        setLabelStatus(state, stateLabel, false);
        setLabelStatus(city, cityLabel, false);
        setLabelStatus(permanentAddress, permanentAddressLabel, false);
        setLabelStatus(localAddress, localAddressLabel, false);

    }

    private boolean isAllFieldValid() {
        return studentNameLabel.getText().equals("✅") && genderLabel.getText().equals("✅") && collegeCourseLabel.getText().equals("✅")
                && dateOfBirthLabel.getText().equals("✅") && studentAadhaarNoLabel.getText().equals("✅") && studentMobileNoLabel.getText().equals("✅")
                && emailLabel.getText().equals("✅") && fatherOccupationLabel.getText().equals("✅") && fatherNameLabel.getText().equals("✅")
                && fatherIncomeLabel.getText().equals("✅") && fatherAadhaarNoLabel.getText().equals("✅") && fatherMobileNoLabel.getText().equals("✅")
                && motherNameLabel.getText().equals("✅") && motherOccupationLabel.getText().equals("✅") && stateLabel.getText().equals("✅")
                && cityLabel.getText().equals("✅") && permanentAddressLabel.getText().equals("✅") && localAddressLabel.getText().equals("✅");
    }
}
