/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementsystem.ui.admin;

import java.awt.Color;
import javax.swing.JOptionPane;
import studentmanagementsystem.service.Services;
import static studentmanagementsystem.utility.Util.allowLetterOrSpace;
import static studentmanagementsystem.utility.Util.isValidDate;
import static studentmanagementsystem.utility.Util.setLabelStatus;

/**
 *
 * @author Abhishek Rajput
 */
public class BatchForm extends javax.swing.JDialog {

    /**
     * Creates new form BatchForm
     */
    public BatchForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        batchName = new javax.swing.JTextField();
        startDate = new javax.swing.JTextField();
        BatchNameLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        batchName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        batchName.setBorder(javax.swing.BorderFactory.createTitledBorder("BatchName"));
        batchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNameActionPerformed(evt);
            }
        });
        batchName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                batchNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                batchNameKeyTyped(evt);
            }
        });

        startDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        startDate.setForeground(new java.awt.Color(153, 153, 153));
        startDate.setText("YYYY-MM-DD");
        startDate.setToolTipText("");
        startDate.setBorder(javax.swing.BorderFactory.createTitledBorder("StartDate"));
        startDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                startDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                startDateFocusLost(evt);
            }
        });
        startDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateActionPerformed(evt);
            }
        });
        startDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                startDateKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                startDateKeyTyped(evt);
            }
        });

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project Image/submit.png"))); // NOI18N
        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submit)
                            .addComponent(batchName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BatchNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(BatchNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(batchName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchNameActionPerformed

    private void batchNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_batchNameKeyReleased
    }//GEN-LAST:event_batchNameKeyReleased

    private void batchNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_batchNameKeyTyped

    }//GEN-LAST:event_batchNameKeyTyped

    private void startDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_startDateFocusGained
        // TODO add your handling code here:
        if (startDate.getText().equals("YYYY-MM-DD")) {
            startDate.setText("");
            startDate.setForeground(Color.black);
        }
    }//GEN-LAST:event_startDateFocusGained

    private void startDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_startDateFocusLost
        // TODO add your handling code here:
        if (startDate.getText().equals("")) {
            startDate.setText("YYYY-MM-DD");
            startDate.setForeground(Color.gray);
        }
    }//GEN-LAST:event_startDateFocusLost

    private void startDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateActionPerformed

    private void startDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_startDateKeyReleased
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '-' || startDate.getText().length() > 9) {
            evt.consume();
        }
        boolean validDate = isValidDate(startDate.getText());
 
        setLabelStatus(startDate, startDateLabel, validDate);
    }//GEN-LAST:event_startDateKeyReleased

    private void startDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_startDateKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '-' || startDate.getText().length() > 9) {
            evt.consume();
        }
        boolean validDate = isValidDate(startDate.getText());
        System.out.println(validDate);
        setLabelStatus(startDate, startDateLabel, validDate);
    }//GEN-LAST:event_startDateKeyTyped

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
       boolean flag = Services.getService().isBatchExist(batchName.getText());
       if(flag){
          JOptionPane.showMessageDialog(rootPane,"Batch Already Existes");
          return ;
       }
       boolean rs =  Services.getService().addBatch(batchName.getText(), startDate.getText());
       if(rs){
           JOptionPane.showMessageDialog(rootPane, "batch Added successfully");
       }else{
           JOptionPane.showMessageDialog(rootPane, "Oops... batch not added");

       }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BatchNameLabel;
    private javax.swing.JTextField batchName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField startDate;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
